Repository fga-eps-mds/2020.2-Lend.it, pull requests merged in 2021-03, with the labels that each got.

#64 Diagrama do Banco de Dados
  _docs/projeto/README.md
  _docs/projeto/db.md
  assets/img/db/der.brM3
  assets/img/db/der.png
  assets/img/db/dl.brM3
  assets/img/db/dl.png
  config/_sidebar.md
Labels: EPS, documentation, modelagem

#92 Docs sprint3
  _docs/gerência/README.md
  _docs/gerência/sprint3/plaining.md
  _docs/gerência/sprint3/results.md
  assets/css/overwrite-docsify-styles.css
  assets/img/sprint3/burndown.png
  assets/img/sprint3/pareamentos.png
  assets/img/sprint3/velocity.png
  config/_sidebar.md
Labels: SM, documentation

#99 Solve #80 Criação de design system
  _docs/produto/design_system.md
Labels: UX/UI

#100 Solve #98 Script de Automação de Commits
  lendmmit
Labels: SM, enhancement

#112 Solve #150 Documentação Sprint 04
  _docs/gerência/README.md
  _docs/gerência/sprint4/plaining.md
  _docs/gerência/sprint4/results.md
  assets/img/sprint4/burndown.png
  assets/img/sprint4/pareamentos.png
  assets/img/sprint4/velocity.png
  config/_sidebar.md
  lendmmit
Labels: SM, documentation

#114 Solve #113 Documentação Sprint 05
  _docs/gerência/README.md
  _docs/gerência/sprint0/plaining.md
  _docs/gerência/sprint0/results.md
  _docs/gerência/sprint1/plaining.md
  _docs/gerência/sprint1/results.md
  _docs/gerência/sprint2/plaining.md
  _docs/gerência/sprint2/results.md
  _docs/gerência/sprint3/results.md
  _docs/gerência/sprint4/results.md
  _docs/gerência/sprint5/plaining.md
  _docs/gerência/sprint5/results.md
  assets/img/sprint5/burndown.png
  assets/img/sprint5/pareamentos.png
  assets/img/sprint5/velocity.png
  config/_sidebar.md
Labels: SM, documentation

#116 Solve #115 Documentação da Sprint 06
  _docs/gerência/README.md
  _docs/gerência/sprint5/plaining.md
  _docs/gerência/sprint5/results.md
  _docs/gerência/sprint6/plaining.md
  _docs/gerência/sprint6/results.md
  assets/img/sprint6/burndown.png
  assets/img/sprint6/pareamentos.png
  assets/img/sprint6/velocity.png
  config/_sidebar.md
Labels: SM, documentation

#117 Solve #83 NFR
  _docs/projeto/README.md
  _docs/projeto/nfr.md
  config/_sidebar.md
Labels: documentation, requirements
